### ISSUE TITLE
Using this module, I am getting a error while making a ssl connection. I have pasted below the module configuration down

### ISSUE THREAD

**Issue by neeraj022** [mrDoctorWho/ejabberd_mod_apns#1]
mod_apns:
    address: "gateway.push.apple.com"
    port: 2195
    certfile: "~/my-ejabberd/etc/cert.pem"
    keyfile: "~/my-ejabberd/etc/key.pem"
    ##password: "password"

**Comment by neeraj022** [comment]
It would be great, if I can get a help on this.

**Comment by mrDoctorWho** [comment]
Hello,

What is that error you're getting? Can you post the erlang exception?

**Comment by neeraj022** [comment]
While making a ssl connection, I am printing the error reason if the connection is unsuccessful. 
Reason printed on the console is : 

[{options,{socket_options,[{mode,binary}]}}]

**Comment by mrDoctorWho** [comment]
So did you manage to fix it in any way?

P.S. I answered you on email, not sure if you noticed.
