### ISSUE TITLE
We are not receiving push notification when large text send by user.

### ISSUE THREAD

**Issue by nileshbacancy** [mrDoctorWho/ejabberd_mod_apns#28]
Hello @mrDoctorWho , @zinid 

We are not receiving a push notification when large text sends by the user.
We are using below mod_apns.erl file.

mod_apns.erl - https://github.com/joanlopez/ejabberd-mod-apns/blob/master/src/mod_apns.erl
Ejabberd version - 16.09

How to truncate text message when send push notification using mod_apns.erl file? 
I am new in erlang so, please help me.

Thanks

**Comment by mrDoctorWho** [comment]
Please do not create any issues related to @joanlopez's mod_apns in my repository.
And don't mention zinid who had just submitted a PR once and is not related to this repository.
