### ISSUE TITLE
Not getting push notification

### ISSUE THREAD

**Issue by piyush-singhal** [mrDoctorWho/ejabberd_mod_apns#4]
I have copied .beam file in ebin folder and updated below configuration in ejabberd.yml

 mod_apns:
    address: "gateway.sandbox.push.apple.com"
    port: 2195
    certfile: "/var/www/html/cert.pem"
    keyfile: "/var/www/html/key.pem"
    password: "password"

And sending given stanza from ios application but still I am not getting any notification, could you please help me over this.

**Comment by mrDoctorWho** [comment]
I believe the issue related to this one: https://github.com/mrDoctorWho/ejabberd_mod_gcm/issues/6.

Please report if that so or not.

**Comment by mrDoctorWho** [comment]
The problem was that the key is encrypted (password-protected) and the module behaved wrong with such keys.

This behaviour is going to be fixed in the next commit.
